"""Event model constants and rules for event extraction.

Contains lists of locations, affected entities (brands/companies), event type
keywords, and severity defaults. This is intentionally data-driven and separate
from logic so it can be updated without changing extraction code.
"""
from __future__ import annotations

# Known location keywords, including city aliases and states/regions.
LOCATION_KEYWORDS = {
    "Chennai": ["Chennai"],
    "Bengaluru": ["Bengaluru", "Bangalore"],
    "Mumbai": ["Mumbai"],
    "Delhi": ["Delhi", "New Delhi"],
    "Kochi": ["Kochi"],
    "Hyderabad": ["Hyderabad"],
    "Pune": ["Pune"],
    "Noida": ["Noida"],
    "Gurugram": ["Gurugram", "Gurgaon"],
    "Ahmedabad": ["Ahmedabad"],
    "Surat": ["Surat"],
    "Sriperumbudur": ["Sriperumbudur"],
    "Tiruvallur": ["Tiruvallur"],
    "Kolkata": ["Kolkata", "Calcutta"],
    "Visakhapatnam": ["Visakhapatnam", "Vizag"],
    "Tamil Nadu": ["Tamil Nadu"],
    "Karnataka": ["Karnataka"],
    "Maharashtra": ["Maharashtra"],
    "Kerala": ["Kerala"],
    "Telangana": ["Telangana"],
    "Gujarat": ["Gujarat"],
    "Uttar Pradesh": ["Uttar Pradesh"],
    "West Bengal": ["West Bengal"],
    "Andhra Pradesh": ["Andhra Pradesh"],
    "India": ["India"],
}

LOCATIONS = list(LOCATION_KEYWORDS.keys())

# Affected entities (brands and companies) with common aliases.
AFFECTED_ENTITY_KEYWORDS = {
    "Samsung": ["Samsung"],
    "Apple": ["Apple"],
    "Dell": ["Dell", "Dell Technologies"],
    "HP": ["HP", "Hewlett Packard"],
    "Lenovo": ["Lenovo"],
    "ASUS": ["ASUS"],
    "Acer": ["Acer"],
    "MSI": ["MSI"],
    "Boat": ["Boat"],
    "JBL": ["JBL"],
    "Sony": ["Sony"],
    "Realme": ["Realme"],
    "POCO": ["POCO"],
    "REDMI": ["REDMI", "Redmi"],
    "Motorola": ["Motorola"],
    "Nothing": ["Nothing"],
    "OnePlus": ["OnePlus"],
    "Noise": ["Noise"],
    "Logitech": ["Logitech"],
    "Zebronics": ["Zebronics"],
    "Corsair": ["Corsair"],
    "Adata": ["Adata"],
    "Kingston": ["Kingston"],
    "SanDisk": ["SanDisk"],
    "Canon": ["Canon"],
    "Nikon": ["Nikon"],
    "Epson": ["Epson"],
    "LG": ["LG"],
    "Panasonic": ["Panasonic"],
    "Philips": ["Philips"],
    "Mi": ["Mi"],
    "Xiaomi": ["Xiaomi"],
    "Reliance": ["Reliance"],
    "Flipkart": ["Flipkart"],
    "Amazon": ["Amazon", "Amazon India"],
    "Havells": ["Havells"],
    "Voltas": ["Voltas"],
    "Bosch": ["Bosch"],
    "Foxconn": ["Foxconn"],
    "Pegatron": ["Pegatron"],
    "Wistron": ["Wistron"],
    "Micron": ["Micron"],
    "Intel": ["Intel"],
    "Qualcomm": ["Qualcomm"],
    "MediaTek": ["MediaTek"],
    "Tata Electronics": ["Tata Electronics"],
    "Dixon Technologies": ["Dixon Technologies", "Dixon"],
}
AFFECTED_ENTITIES = list(AFFECTED_ENTITY_KEYWORDS.keys())

# Map event type keywords (lowercase) to canonical event types.
EVENT_KEYWORDS = {
    # Weather related
    "heavy rain": "Heavy Rain",
    "rain": "Heavy Rain",
    "flood": "Flood",
    "cyclone": "Cyclone",
    "storm": "Storm",
    "heatwave": "Extreme Heat",
    "extreme heat": "Extreme Heat",
    "drought": "Drought",
    # Logistics
    "port congestion": "Port Congestion",
    "shipping delay": "Shipping Delay",
    "transport disruption": "Transport Disruption",
    "road closure": "Road Closure",
    "supply chain disruption": "Supply Chain Disruption",
    "delivery delay": "Delivery Delay",
    "transport delay": "Transport Delay",
    "logistics issue": "Transport Disruption",
    "logistics disruption": "Transport Disruption",
    # Manufacturing
    "factory shutdown": "Factory Shutdown",
    "production halt": "Production Halt",
    "production disruption": "Production Disruption",
    "power outage": "Power Outage",
    "factory fire": "Factory Fire",
    "industrial accident": "Industrial Accident",
    "production delay": "Production Delay",
    # Supply
    "supply shortage": "Supply Shortage",
    "component shortage": "Component Shortage",
    "semiconductor shortage": "Semiconductor Shortage",
    "chip shortage": "Semiconductor Shortage",
    "raw material shortage": "Raw Material Shortage",
    # Market / trade
    "import restriction": "Import Restriction",
    "export restriction": "Export Restriction",
    "tariff": "Tariff",
    "trade disruption": "Trade Disruption",
    "strike": "Strike",
    # Retail / demand
    "festival sale": "Festival Sales",
    "festival sales": "Festival Sales",
    "electronics demand": "Electronics Demand",
    "demand spike": "Electronics Demand",
    "warehouse disruption": "Warehouse Disruption",
    "warehouse fire": "Warehouse Disruption",
    "supply chain": "Supply Chain Disruption",
}

# Severity defaults per event type
SEVERITY_DEFAULT = {
    "Light Rain": "Low",
    "Moderate Rain": "Medium",
    "Thunderstorm": "High",
    "Heavy Rain": "Medium",
    "Flood": "High",
    "Cyclone": "Critical",
    "Storm": "Medium",
    "Extreme Heat": "Medium",
    "Drought": "High",
    "Port Congestion": "High",
    "Shipping Delay": "Medium",
    "Transport Delay": "Medium",
    "Transport Disruption": "Medium",
    "Road Closure": "Medium",
    "Supply Chain Disruption": "High",
    "Delivery Delay": "Medium",
    "Factory Shutdown": "Critical",
    "Production Halt": "Critical",
    "Production Disruption": "High",
    "Power Outage": "Critical",
    "Factory Fire": "Critical",
    "Industrial Accident": "Critical",
    "Production Delay": "High",
    "Supply Shortage": "High",
    "Component Shortage": "High",
    "Semiconductor Shortage": "High",
    "Raw Material Shortage": "High",
    "Import Restriction": "High",
    "Export Restriction": "High",
    "Tariff": "Medium",
    "Trade Disruption": "High",
    "Strike": "High",
    "Festival Sales": "Low",
    "Electronics Demand": "Low",
    "Warehouse Disruption": "High",
    "Supply Chain": "High",
}

# Source priorities (for reference)
SOURCES = ["news", "weather"]
